favicon: /img/favicon.png

apple_touch_icon: /img/favicon.png

tab_title_separator: " - "

force_https: false

code:
  copy_btn: true
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      style: "Solarized Dark"
      bg_color: true
    prismjs:
      style: "default"
      preprocess: true

fun_features:
  typing:
    enable: true
    typeSpeed: 70
    cursorChar: "_"
    loop: false
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right
    visible: hover
    icon: ""
  progressbar:
    enable: true
    height_px: 3
    color: "#9575CD"
    options: { showSpinner: false, trickleSpeed: 100 }

dark_mode:
  enable: true
  default: auto

color:
  body_bg_color: "#eee"
  body_bg_color_dark: "#251640"

  # 顶部菜单背景色
  # Color of navigation bar background
  navbar_bg_color: "#7108B2"
  navbar_bg_color_dark: "#4B04A8"

  # 顶部菜单字体色
  # Color of navigation bar text
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"

  # 全局字体色
  # Color of global text
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"

  # 全局次级字体色（摘要、简介等位置）
  # Color of global secondary text (excerpt, introduction, etc.)
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"

  # 文章正文字体色
  # Color of post text
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"

  # 文章正文字体色（h1 h2 h3...）
  # Color of Article heading (h1 h2 h3...)
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"

  # 文章超链接字体色
  # Color of post link
  post_link_color: "#3c9306"
  post_link_color_dark: "#006800"

  # 超链接悬浮时字体色
  # Color of link when hovering
  link_hover_color: "#3c9306"
  link_hover_color_dark: "#3c9306"

  # 超链接悬浮背景色
  # Color of link background when hovering
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#0000003a"

  # 主面板背景色
  # Color of main board
  board_color: "#fff"
  board_color_dark: "#3b2365"

font:
  font_size: 16px
  font_family:
  code_font_size: 85%

custom_js:
  - '/js/live2dcubismcore.min.js'
  - 'https://cdn.jsdelivr.net/gh/dylanNew/live2d@fd9fd40/webgl/Live2D/lib/live2d.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/pixi.js/5.3.10/pixi.min.js'
  - 'https://cdn.jsdelivr.net/npm/pixi-live2d-display@0.3.1/dist/index.js'
  - 'https://cdn.jsdelivr.net/gh/perqin/live2d-widget@v5+f9bc441/autoload.js'

custom_css:
  - https://cdn.jsdelivr.net/npm/font-awesome/css/font-awesome.min.css

custom_head: ''

custom_html: ''

web_analytics:
  enable: true
  cnzz: '1279692316'
  leancloud:
    app_id:
    app_key:
    server_url:

lazyload:
  enable: true
  loading_img: /img/loading.gif
  onlypost: false
  offset_factor: 2

iconfont: //at.alicdn.com/t/font_1736178_kmeydafke9r.css

navbar:
  blog_title: ''
  ground_glass:
    enable: false
    px: 3
    alpha: 0.7
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-archive-fill" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user-fill" }
    - { key: 'links', link: '/links/', icon: 'iconfont icon-link-fill' }

search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  field: post
  content: true

banner:
  parallax: true
  width_height_ratio: 1.0

scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true

scroll_top_arrow:
  enable: true


footer:
  content: '
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a>
    <i class="iconfont icon-love"></i>
    <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a>
  '
  statistics:
    enable: false
    source: "busuanzi"
    pv_format: "总访问量 {} 次"
    uv_format: "总访客数 {} 人"
  beian:
    enable: false
    icp_text: 京ICP证123456号
    police_text: 京公网安备12345678号
    police_code: 12345678
    police_icon: /img/police_beian.png

index:
  banner_img: /img/default.png
  banner_img_height: 100
  banner_mask_alpha: 0.3
  slogan:
    enable: true
    text: ''
    api:
      enable: false
  auto_excerpt:
    enable: true
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: true
  post_sticky:
    enable: true
    icon: "iconfont icon-top"

post:
  banner_img: /img/default.png
  banner_img_height: 70
  banner_mask_alpha: 0.3
  default_index_img:
  meta:
    author:
      enable: false
    date:
      enable: true
      format: "LL a"
    wordcount:
      enable: true
      format: "{} 字"
    min2read:
      enable: true
      format: "{} 分钟"
      words: 100
    views:
      enable: false
      source: "busuanzi"
      format: "{} 次"
  updated:
    enable: false
    content: 本文最后更新于：
    relative: false
  toc:
    enable: true
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  copyright:
    enable: true
    content: '本博客所有文章除特别声明外，均采用 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh" rel="nofollow noopener">CC BY-SA 4.0 协议</a> ，转载请注明出处！'
  prev_next:
    enable: true
  custom:
    enable: false
    content: '<img src="https://octodex.github.com/images/jetpacktocat.png" class="rounded mx-auto d-block mt-5" style="width:150px; height:150px;">'
  image_zoom:
    enable: true
    img_url_replace: ['', '']
  footnote:
    enable: false
    header: ''
  math:
    enable: false
    specific: false
    engine: mathjax
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  comments:
    enable: true
    type: disqus

disqus:
  shortname: 'perqin-github-io'
  disqusjs: false
  apikey:

archive:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:

category:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:
  order_by: "-length"
  collapse_depth: 0
  post_order_by: "-date"
  post_limit: 10

tag:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 80
  banner_mask_alpha: 0.3
  subtitle:
  tagcloud:
    min_font: 15
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

about:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:
  avatar: /img/favicon.png
  name: "Perqin"
  intro:
  icons:
    - { class: "iconfont icon-bilibili", link: "https://space.bilibili.com/23285782", tip: "Bilibili" }
    - { class: "iconfont icon-github-fill", link: "https://github.com/perqin", tip: "GitHub" }
    - { class: "iconfont icon-mail", link: "mailto:perqinxie@gmail.com", tip: "Mail" }
    - { class: "iconfont icon-twitter-fill", link: "https://twitter.com/perqinxie", tip: "Twitter" }

page:
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3

page404:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 85
  banner_mask_alpha: 0.3
  subtitle: "Page not found"

links:
  enable: true
  banner_img: /img/default.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  subtitle:
  items:
    - {
      title: "BirdZhang's Blog",
      link: "https://birdzhang.xyz/"
    }
    - {
      title: "Dospy-梦影决幻",
      link: "https://weibo.com/435312561"
    }
    - {
      title: "浮游大陆",
      link: "https://blog.qshen.cc/"
    }
    - {
      title: "FrodoLuo",
      link: "https://www.frodoluo.ink/blog"
    }
  onerror_avatar: /img/avatar.png
  custom:
    enable: false
    content: '<hr><p>在下方留言申请加入我的友链，按如下格式提供信息：</p><ul><li>博客名：Fluid</li><li>简介：Fluid 主题官方博客</li><li>链接：https://hexo.fluid-dev.com</li><li>图片：https://hexo.fluid-dev.com/img/favicon.png</li></ul>'
  comments:
    enable: false
    type: disqus

static_prefix:
  internal_js: /js
  internal_css: /css
  internal_img: /img
  anchor: https://cdn.jsdelivr.net/npm/anchor-js@4.3.0/
  github_markdown: https://cdn.jsdelivr.net/npm/github-markdown-css@4.0.0/
  jquery: https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/
  bootstrap: https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/
  highlightjs: https://cdn.jsdelivr.net/npm/highlight.js@10.6.0/
  prismjs: https://cdn.jsdelivr.net/npm/prismjs@1.23.0/
  tocbot: https://cdn.jsdelivr.net/npm/tocbot@4.12.2/dist/
  typed: https://cdn.jsdelivr.net/npm/typed.js@2.0.11/lib/
  fancybox: https://cdn.jsdelivr.net/npm/@fancyapps/fancybox@3.5.7/dist/
  nprogress: https://cdn.jsdelivr.net/npm/nprogress@0.2.0/
  mathjax: https://cdn.jsdelivr.net/npm/mathjax@3.1.2/es5/
  katex: https://cdn.jsdelivr.net/npm/katex@0.13.0/dist/
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/
  clipboard: https://cdn.jsdelivr.net/npm/clipboard@2.0.8/dist/
  mermaid: https://cdn.jsdelivr.net/npm/mermaid@8.9.2/dist/
  valine: https://cdn.jsdelivr.net/npm/valine@1.4.14/dist/
  waline: https://cdn.jsdelivr.net/npm/@waline/client@0.14.8/dist/
  gitalk: https://cdn.jsdelivr.net/npm/gitalk@1.7.2/dist/
  disqusjs: https://cdn.jsdelivr.net/npm/disqusjs@1.3.0/dist/
  twikoo: https://cdn.jsdelivr.net/npm/twikoo@1.3.0/dist/
  hint: https://cdn.jsdelivr.net/npm/hint.css@2.7.0/
